/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExecutivoIndexRouteImport } from './routes/executivo.index'
import { Route as ManualConcluidoRouteImport } from './routes/manual/concluido'
import { Route as ManualChapterRouteImport } from './routes/manual/$chapter'
import { Route as ExecutivoUsuariosRouteImport } from './routes/executivo.usuarios'
import { Route as ExecutivoInvestidoresRouteImport } from './routes/executivo.investidores'
import { Route as ExecutivoIaRouteImport } from './routes/executivo.ia'
import { Route as ExecutivoHomeRouteImport } from './routes/executivo.home'
import { Route as ExecutivoDashboardRouteImport } from './routes/executivo.dashboard'
import { Route as ExecutivoConhecimentoRouteImport } from './routes/executivo.conhecimento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutivoIndexRoute = ExecutivoIndexRouteImport.update({
  id: '/executivo/',
  path: '/executivo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualConcluidoRoute = ManualConcluidoRouteImport.update({
  id: '/manual/concluido',
  path: '/manual/concluido',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualChapterRoute = ManualChapterRouteImport.update({
  id: '/manual/$chapter',
  path: '/manual/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutivoUsuariosRoute = ExecutivoUsuariosRouteImport.update({
  id: '/executivo/usuarios',
  path: '/executivo/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutivoInvestidoresRoute = ExecutivoInvestidoresRouteImport.update({
  id: '/executivo/investidores',
  path: '/executivo/investidores',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutivoIaRoute = ExecutivoIaRouteImport.update({
  id: '/executivo/ia',
  path: '/executivo/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutivoHomeRoute = ExecutivoHomeRouteImport.update({
  id: '/executivo/home',
  path: '/executivo/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutivoDashboardRoute = ExecutivoDashboardRouteImport.update({
  id: '/executivo/dashboard',
  path: '/executivo/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutivoConhecimentoRoute = ExecutivoConhecimentoRouteImport.update({
  id: '/executivo/conhecimento',
  path: '/executivo/conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/executivo/conhecimento': typeof ExecutivoConhecimentoRoute
  '/executivo/dashboard': typeof ExecutivoDashboardRoute
  '/executivo/home': typeof ExecutivoHomeRoute
  '/executivo/ia': typeof ExecutivoIaRoute
  '/executivo/investidores': typeof ExecutivoInvestidoresRoute
  '/executivo/usuarios': typeof ExecutivoUsuariosRoute
  '/manual/$chapter': typeof ManualChapterRoute
  '/manual/concluido': typeof ManualConcluidoRoute
  '/executivo/': typeof ExecutivoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/executivo/conhecimento': typeof ExecutivoConhecimentoRoute
  '/executivo/dashboard': typeof ExecutivoDashboardRoute
  '/executivo/home': typeof ExecutivoHomeRoute
  '/executivo/ia': typeof ExecutivoIaRoute
  '/executivo/investidores': typeof ExecutivoInvestidoresRoute
  '/executivo/usuarios': typeof ExecutivoUsuariosRoute
  '/manual/$chapter': typeof ManualChapterRoute
  '/manual/concluido': typeof ManualConcluidoRoute
  '/executivo': typeof ExecutivoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/executivo/conhecimento': typeof ExecutivoConhecimentoRoute
  '/executivo/dashboard': typeof ExecutivoDashboardRoute
  '/executivo/home': typeof ExecutivoHomeRoute
  '/executivo/ia': typeof ExecutivoIaRoute
  '/executivo/investidores': typeof ExecutivoInvestidoresRoute
  '/executivo/usuarios': typeof ExecutivoUsuariosRoute
  '/manual/$chapter': typeof ManualChapterRoute
  '/manual/concluido': typeof ManualConcluidoRoute
  '/executivo/': typeof ExecutivoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/executivo/conhecimento'
    | '/executivo/dashboard'
    | '/executivo/home'
    | '/executivo/ia'
    | '/executivo/investidores'
    | '/executivo/usuarios'
    | '/manual/$chapter'
    | '/manual/concluido'
    | '/executivo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/executivo/conhecimento'
    | '/executivo/dashboard'
    | '/executivo/home'
    | '/executivo/ia'
    | '/executivo/investidores'
    | '/executivo/usuarios'
    | '/manual/$chapter'
    | '/manual/concluido'
    | '/executivo'
  id:
    | '__root__'
    | '/'
    | '/executivo/conhecimento'
    | '/executivo/dashboard'
    | '/executivo/home'
    | '/executivo/ia'
    | '/executivo/investidores'
    | '/executivo/usuarios'
    | '/manual/$chapter'
    | '/manual/concluido'
    | '/executivo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExecutivoConhecimentoRoute: typeof ExecutivoConhecimentoRoute
  ExecutivoDashboardRoute: typeof ExecutivoDashboardRoute
  ExecutivoHomeRoute: typeof ExecutivoHomeRoute
  ExecutivoIaRoute: typeof ExecutivoIaRoute
  ExecutivoInvestidoresRoute: typeof ExecutivoInvestidoresRoute
  ExecutivoUsuariosRoute: typeof ExecutivoUsuariosRoute
  ManualChapterRoute: typeof ManualChapterRoute
  ManualConcluidoRoute: typeof ManualConcluidoRoute
  ExecutivoIndexRoute: typeof ExecutivoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executivo/': {
      id: '/executivo/'
      path: '/executivo'
      fullPath: '/executivo/'
      preLoaderRoute: typeof ExecutivoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual/concluido': {
      id: '/manual/concluido'
      path: '/manual/concluido'
      fullPath: '/manual/concluido'
      preLoaderRoute: typeof ManualConcluidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual/$chapter': {
      id: '/manual/$chapter'
      path: '/manual/$chapter'
      fullPath: '/manual/$chapter'
      preLoaderRoute: typeof ManualChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executivo/usuarios': {
      id: '/executivo/usuarios'
      path: '/executivo/usuarios'
      fullPath: '/executivo/usuarios'
      preLoaderRoute: typeof ExecutivoUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executivo/investidores': {
      id: '/executivo/investidores'
      path: '/executivo/investidores'
      fullPath: '/executivo/investidores'
      preLoaderRoute: typeof ExecutivoInvestidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executivo/ia': {
      id: '/executivo/ia'
      path: '/executivo/ia'
      fullPath: '/executivo/ia'
      preLoaderRoute: typeof ExecutivoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executivo/home': {
      id: '/executivo/home'
      path: '/executivo/home'
      fullPath: '/executivo/home'
      preLoaderRoute: typeof ExecutivoHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executivo/dashboard': {
      id: '/executivo/dashboard'
      path: '/executivo/dashboard'
      fullPath: '/executivo/dashboard'
      preLoaderRoute: typeof ExecutivoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executivo/conhecimento': {
      id: '/executivo/conhecimento'
      path: '/executivo/conhecimento'
      fullPath: '/executivo/conhecimento'
      preLoaderRoute: typeof ExecutivoConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExecutivoConhecimentoRoute: ExecutivoConhecimentoRoute,
  ExecutivoDashboardRoute: ExecutivoDashboardRoute,
  ExecutivoHomeRoute: ExecutivoHomeRoute,
  ExecutivoIaRoute: ExecutivoIaRoute,
  ExecutivoInvestidoresRoute: ExecutivoInvestidoresRoute,
  ExecutivoUsuariosRoute: ExecutivoUsuariosRoute,
  ManualChapterRoute: ManualChapterRoute,
  ManualConcluidoRoute: ManualConcluidoRoute,
  ExecutivoIndexRoute: ExecutivoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
